# service running port on machine
server.port: 9097

# service name - when register with eureka this name which get register
spring:
  application:
    name: age-service

# application level logging
logging:
  level:
    ROOT: DEBUG

# register with same zone eureka server
# zone's eureka server configuration
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: https://eureka-server-cf.cfapps.io/eureka/
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    nonSecurePort: 80
