server.port: 9098

spring:
  application:
    name: dob-service

logging:
  level:
    ROOT: DUBUG

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://eureka-server-cf.cfapps.io/eureka/
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    nonSecurePort: 80
    #https://eureka-server-cf.eu-gb.mybluemix.net/eureka/
    #http://localhost:8761/eureka/
